travis:
  secure:
    BINSTAR_TOKEN: V/AffsKJKYngxlwpbNgYkrF1JI9cFR+354lCwMaDam9aX8kCUXnKjdVLJ7TNFMEJ6wP8DmcYJIs2con50Ddz4k1XKqRbS6cOj2uBFxuXZYlVhAJivRHTomzEuDr7iJ9FTzpT2jLTC05mHNEre5URwHj9PtnmD8IqVrWmdLvnlXhlWDVN7cXW+1lSxmHKs0ijyDT+NCh27WjJzukyPhKFXmsBHyv5RjSivtHaDfWxjHBG+4ZX5PmnWX3zRqMcExCHIRfzA4FMEJsJRuAZiYBOu7QzAxJRtTjweXNQ0w2cOKEuWv+GBJ07Ea7/993sSEqQJ1b2eX55yDgBys6miNYs8FU2B2rySQ+KtFyCMhmErrDvgSNM0Iaoj1sN7XP03IjsJAnAYINQFoGGoRHJwyAUm6gSeXXhzw6GK81IxsQvEOwC+q1CGDGjjSUqsC0gwp12ilmbck7zC1tWNrLoAP8AA75Rko8mtoKIYWfoGLfXxlgV2LRUqbmD86/XwQpDwUeNwlU7f4Jjep5xyRLnszApB/S5o5mJlg13DG0Kg0k82okKZ2HK4bPVHUDEcr7vdUIUBz8fn3OByI73A2Eef4zGGFAySORDy0nHIhC7XcN6SnXHp1DyLCZDZrlpBeTudRQ0WTMJHNpHTUlFCmorOPU7ZPQadaXbPo+hAVi6QRVebeI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
